"use strict";

const ROOM_STATUS = Object.freeze({
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  CLEANING: "CLEANING",
  WAITING_INSPECTION: "WAITING_INSPECTION",
  INSPECTING: "INSPECTING",
  READY: "READY",
  MAINTENANCE: "MAINTENANCE",
  BLOCKED: "BLOCKED",
  OUT_OF_SERVICE: "OUT_OF_SERVICE",
});

const ROOM_EVENT = Object.freeze({
  ROOM_ASSIGNED: "ROOM_ASSIGNED",
  INSPECTOR_ASSIGNED: "INSPECTOR_ASSIGNED",
  CLEANING_STARTED: "CLEANING_STARTED",
  CLEANING_FINISHED: "CLEANING_FINISHED",
  INSPECTION_STARTED: "INSPECTION_STARTED",
  READY_FOR_GUEST: "READY_FOR_GUEST",
  ISSUE_REPORTED: "ISSUE_REPORTED",
  SUPPLIES_REQUESTED: "SUPPLIES_REQUESTED",
  PAGER_ASSIGNED: "PAGER_ASSIGNED",
  MAINTENANCE_CREATED: "MAINTENANCE_CREATED",
});

const LEGACY_STATUS_BY_CORE_STATUS = Object.freeze({
  [ROOM_STATUS.PENDING]: "Pending",
  [ROOM_STATUS.ASSIGNED]: "Pending",
  [ROOM_STATUS.CLEANING]: "In Progress",
  [ROOM_STATUS.WAITING_INSPECTION]: "Ready for Inspection",
  [ROOM_STATUS.INSPECTING]: "Inspection Started",
  [ROOM_STATUS.READY]: "Ready for Guest",
  [ROOM_STATUS.MAINTENANCE]: "Maintenance",
  [ROOM_STATUS.BLOCKED]: "Blocked",
  [ROOM_STATUS.OUT_OF_SERVICE]: "Out of Service",
});

module.exports = {
  ROOM_STATUS,
  ROOM_EVENT,
  LEGACY_STATUS_BY_CORE_STATUS,
};
